name: to_do_list
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_slidable: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  fonts:
    - family: Cleanow
      fonts:
        - asset: lib/assets/fonts/Cleanow.ttf
          weight: 700

    - family: PORKYS
      fonts:
        - asset: lib/assets/fonts/PORKYS_.ttf
          weight: 700